<? 
  $data = $this -> get_data( $inc );   
  $message         = $this -> get_data( "message" );
  $param           = $this -> get_data( "param" );
  $data_references = $this -> get_data( "data_references" );
  $data_forms      = $this -> get_data( "data_forms" );
  $type            = $this -> get_data( "type" );
?>
  <p class="caption" align="center"><?= Util :: s_param('action')=="add" ? "Добавить" : "Редактировать" ?> Поле: <?= $data -> title ?></p>

<form method="POST" action="index.php?menu=field&cmd=<?= Util :: s_param('action') ?>&id=<?= $data -> id ?>&item_id=<?= $param["item_id"] ?>" onsubmit="return validateComplete(this)">
<b><?= $message  ?></b><br />
<table bgcolor="#efefef" cellspacing="0" cellpadding="5" border="0" align="center" width="100%">
  
  <tr><td>Тип:</td>
  <td>
   <select name="type">
    <option value="0">Нет</option> 
    <? foreach ( $type as $item) { ?>
    <option value="<?= $item["id"] ?>" <?= $data -> type == $item["id"] ? 'selected' : '' ?>><?= $item["title"] ?></option>
    <? } ?>
   </select>
  </td></tr>
  
  <tr><td>Титл:</td><td><textarea name="title" style="width: 100%;" rows="10"><?= $data -> title ?></textarea></td></tr>
  <tr><td>Имя:</td><td><input type="text" name="name" value="<?= $data -> name ?>" style="width: 100%;"></td></tr>
  
  <tr><td>Форма:</td>
  <td>
   <select name="form_id">
    <option value="0">Нет</option> 
    <? foreach ( $data_forms as $item) { ?>
    <? if (empty($param["item_id"])) { ?>
    <option value="<?= $item["id"] ?>" <?= $data -> form_id == $item["id"] ? 'selected' : '' ?>><?= $item["id"] ?></option>
    <? } else { ?>
    <option value="<?= $item["id"] ?>" <?= $param["item_id"] == $item["id"] ? 'selected' : '' ?>><?= $item["id"] ?></option>
    <? } ?>
    <? } ?>
   </select>
  </td></tr>
  
  <tr><td>Референсес:</td>
  <td>
   <select name="reference_id">
    <option value="0">Нет</option> 
    <? foreach ( $data_references as $item) { ?>
    <option value="<?= $item["id"] ?>" <?= $data -> reference_id == $item["id"] ? 'selected' : '' ?>><?= $item["title"] ?></option>
    <? } ?>
   </select>
  </td></tr>
  
  <tr><td>Обязательное:</td>
  <td>
   <select name="required">
    <option value="0" <?= !$data -> required ? "selected" : "" ?>>Нет</option> 
    <option value="1" <?= $data -> required ? "selected" : "" ?>>Да</option>    
   </select>
  </td>
  </tr>
  
  <tr><td>Пустая строка:</td>
  <td>
   <select name="empty_string">
    <option value="0" <?= !$data -> empty_string ? "selected" : "" ?>>Нет</option> 
    <option value="1" <?= $data -> empty_string ? "selected" : "" ?>>Да</option>    
   </select>
  </td>
  </tr>
  
  <tr><td>Сортировка:</td><td><input type="text" name="sort" value="<?= $data -> sort ? $data -> sort : 0 ?>" style="width: 10%;"></td></tr>
  
  <tr><td>Сохранять:</td>
  <td>
   <select name="save">
    <option value="0" <?= !$data -> save ? "selected" : "" ?>>Нет</option> 
    <option value="1" <?= $data -> save ? "selected" : "" ?>>Да</option>    
   </select>
  </td>
  </tr>
  
  <tr><td>Описание:</td><td><textarea name="description" rows="10" style="width: 100%;"><?= $data -> description ?></textarea></td></tr> 
    
  <tr><td colspan="2"><input type="submit" value="<?= Util :: s_param('action')=="add" ? "Добавить" : "Сохранить" ?>"></td></tr>
  </table>
  <p align="left"><a href="?menu=field&item_id=<?= $param["item_id"] ?>">Все поля</a></p>
  <p>&nbsp;</p>
</form>
