<? $data = $this -> get_data( $inc );     
   $param = $this ->  get_data( "param" );
   
?>
<table cellpadding="5" cellspacing="0" width="100%" border="0">
<tr valign="top">
  
 <td align="left" width="20%" nowrap>
 <form action="index.php?menu=references" name="search" method="post">
 <input type="text" name="filter" value="<?= $param["filter"] ?>">&nbsp;&nbsp;
 <input type="submit" value="Найти">
 </form>
 </td>
 
</tr>
</table>

<h1>References </h1>
  <b><?= $param["message"]  ?></b>

    <table width="90%">
    <tr>
     <td width="100%" align="right"> Страниц: <?= HTML :: pages_ext( $param["limit"], $param["record_count"], $param["group_limit"], $param["pages"] ,  "index.php?menu=references&" ) ?></td>
    </tr>
    </table>

  
  <table cellspacing="2" cellpadding="5" border="0" width="100%">
  <form method="POST" action="index.php?menu=references&action=edit&cmd=add&pages=<?= $param["pages"] ?>">
  <tr bgcolor="silver">
  <th width="40%">Референсес</th><th width="50%">Описание</th><th>&nbsp;</th><th>&nbsp;</th>
  
 <?
   if( count( $data ) > 0 ) { 
    foreach( $data as $item) {
  ?> 
  
  </tr>
  
    <tr>    
    <td width="40%"><input type="text" name="all_spr[<?= $item["id"] ?>]" value="<?= $item["title"] ?>" style="width:100%;"></td>
    <td width="50%"><input type="text" name="all_description[<?= $item["id"] ?>]" value="<?= $item["description"] ?>" style="width:100%;"></td>
	<td>
	<a href="index.php?menu=refitem&item_id=<?= $item["id"] ?>">Значения</a>
	</td>
    <td width="10%" align="center"><a href="index.php?menu=references&cmd=del&id=<?= $item["id"] ?>" class="menu" onclick="return ConfirmDelete()">Удалить</a></td>
   <tr>
   
  <? 
     }  
   } ?>
</table>    

   <table width="90%">
    <tr>
     <td width="100%" align="right">Страниц: <?= HTML :: pages_ext( $param["limit"], $param["record_count"], $param["group_limit"], $param["pages"] ,  "index.php?menu=references&" ) ?></td>
    </tr>
    </table>
   <br />
   
   <table cellspacing="2" cellpadding="5" border="0" width="100%"> 
   <tr>
    <td width="40%"><input type="text" name="title" style="width:100%;"></td>
	<td width="50%">
	<input type="text" name="description" value="" style="width:100%;">
	</td>
    <td width="10%" align="right"><input type="submit" value="Сохранить"></td>
   </tr> 
 </table>
 </form>
 <p>&nbsp;</p>