<? $data = $this -> get_data( $inc );     
   $param = $this -> get_data( "param" );
   $references = $this -> get_data( "references" );
?>
<table cellpadding="5" cellspacing="0" width="100%" border="0">
<tr valign="top">
 <td align="left" width="15%" nowrap>
 <a href="index.php?menu=refitem&action=add&item_id=<?= $references -> id ?>">Добавить значение</a>
 </td>
 <td align="left" width="20%" nowrap>
 <form action="index.php?menu=refitem&&item_id=<?= $references -> id ?>" name="search" method="post">
 <input type="text" name="filter" value="<?= $param["filter"] ?>">&nbsp;&nbsp;
 <input type="submit" value="Найти">
 </form>
 </td>
 <td width="65%" align="right">Страниц : <?= HTML :: pages_ext( $param["limit"], $param["record_count"], $param["group_limit"], $param["pages"] ,  "index.php?menu=refitem&action=add&item_id=".$references -> id."&" ) ?></td>
</tr>
</table>
  <h1><?= $references -> title ?></h1>
  <b><?= $param["message"]  ?></b><br />
   <form method="POST" action="index.php?menu=refitem&action=update&item_id=<?= $references -> id ?>&pages=<?= $param["pages"] ?>">
  <table cellspacing="2" cellpadding="5" border="0" width="100%">
  <tr bgcolor="silver">
  <th width="5%">Id</th><th width="50%">Титл</th><th width="15%">Значение</th><th width="10%">Сортировка</th><th width="10%">&nbsp;</th><th width="10%">&nbsp;</th>
 <?
   if( count( $data ) > 0 ) { 
    foreach( $data as $item) {
  ?> 
  </tr>
   <tr bgcolor="#efefef">
   <td><?= $item["id"] ?></td>
   <td><?= empty( $item["title"] ) ? "нет титла" :  $item["title"] ?></td>
   <td><?= $item["value"] ?></td>
   <td align="center"><input type="hidden" name="all_id[<?= $item["id"] ?>]" value="<?= $item["id"] ?>">
   <input type="text" name="all_sort[<?= $item["id"] ?>]" value="<?= $item["sort"] ?>" style="width:50%;"></td>
   <td><a href="index.php?menu=refitem&action=edit&id=<?= $item["id"] ?>&item_id=<?= $references -> id ?>" class="menu">редактировать</a></td>
   <td><a href="index.php?menu=refitem&action=list&cmd=del&id=<?= $item["id"] ?>&item_id=<?= $references -> id ?>" class="menu" onclick="return ConfirmDelete()">удалить</a></td>
   <tr>
  <? 
     }  
   } ?> 
 </table>
 <p align="right"><input type="submit" value="Сохранить"></p>
 </form>
 <p align="left"><a href="?menu=references">References</a></p>
<p>&nbsp;</p>