<? $data = $this -> get_data( $inc );     
   $param = $this -> get_data( "param" );
   $field = $this -> get_data( "field" );
   $data_node = $this -> get_data( "data_node" );
?>
<table cellpadding="5" cellspacing="0" width="100%" border="0">
<tr valign="top">
 <td width="65%" align="right">Страниц : <?= HTML :: pages_ext( $param["limit"], $param["record_count"], $param["group_limit"], $param["pages"] ,  "index.php?menu=condition&" ) ?></td>
</tr>
</table>

  <b><?= $param["message"]  ?></b><br />
  <form method="POST" action="index.php?menu=condition&cmd=add">
  <table cellspacing="2" cellpadding="5" border="0" width="100%">
  <tr bgcolor="silver">
   <th width="20%">Переход с узла</th><th width="20%">Посещенный узел</th><th width="20%">Условие перехода(поле)</th><th width="20%">Значение поля</th><th width="20%">Переход на узел</th>
  </tr>
  <tr>
   <td align="center">
   <select name="node_id">
    <option value="0">Нет</option> 
    <? foreach ( $data_node as $item) { ?>   
    <option value="<?= $item["id"] ?>"><?= $item["id"] ?></option>   
    <? } ?>
   </select>
   
   </td>
   <td align="center"><input type="text" name="if_visited_node" value="" style="width: 100%;"></td>
   <td align="center">
   <select name="if_field" style="width: 200px;">
    <option value="0">Нет</option> 
    <? foreach ( $field as $item) { ?>   
    <option value="<?= $item["id"] ?>"><?= $item["title"] ?></option>   
    <? } ?>
   </select>
   </td>
   <td align="center"><input type="text" name="if_field_value" value="" style="width: 100%;"></td>
   <td align="center">
   <select name="to_node">
    <option value="0">Нет</option> 
    <? foreach ( $data_node as $item) { ?>   
    <option value="<?= $item["id"] ?>"><?= $item["id"] ?></option>   
    <? } ?>
   </select>
   </td>
  </tr>
  </table>
  <p align="right"><input type="submit" value="Добавить"></p>
  </form>
  <p>&nbsp;</p>
  <table cellspacing="2" cellpadding="5" border="0" width="100%">
  <tr bgcolor="silver">
  <th width="20%">Переход с узла</th><th width="20%">Посещенный узел</th><th width="20%">Условие перехода(поле)</th><th width="20%">Значение поля</th><th width="20%">Переход на узел</th>
  </tr>
 <?
   if( count( $data ) > 0 ) { 
    foreach( $data as $item) {
  ?> 
   <tr bgcolor="#efefef">
   <td><?= $item["node_id"] ?></td>
   <td><?= $item["if_visited_node"] ?></td>
   <td><?= $item["if_field"] ?></td>
   <td><?= $item["if_field_value"] ?></td>
   <td><?= $item["to_node"] ?></td>
  <tr>
  <? 
     }  
   } ?> 
 </table>

<p>&nbsp;</p>