<? $data = $this -> get_data( $inc );     
   $param = $this -> get_data( "param" );
   
?>
<table cellpadding="5" cellspacing="0" width="100%" border="0">
<tr valign="top">
 <td align="left" width="15%" nowrap>
 <a href="index.php?menu=form&action=add&item_id=<?= $param["item_id"] ?>">Добавить форму</a>
 </td>
 <td align="left" width="20%" nowrap>
 <form action="index.php?menu=form&item_id=<?= $param["item_id"] ?>" name="search" method="post">
 <input type="text" name="filter" value="<?= $param["filter"] ?>">&nbsp;&nbsp;
 <input type="submit" value="Найти">
 </form>
 </td>
 <td width="65%" align="right">Страниц : <?= HTML :: pages_ext( $param["limit"], $param["record_count"], $param["group_limit"], $param["pages"] ,  "index.php?menu=form&" ) ?></td>
</tr>
</table>
  <?= !empty($param["item_id"]) ? '<h1>Форма узла ID = '.$param["item_id"].'</h1>' : '' ?>
  <b><?= $param["message"]  ?></b><br />
  <table cellspacing="2" cellpadding="5" border="0" width="100%">
  <tr bgcolor="silver">
  <th width="10%">Id</th><th width="20%">Титл</th><th width="15%">Id узла</th><th width="15%">Проект</th><th width="10%">Сохранение</th><th width="10%">Поля</th><th width="10%">&nbsp;</th><th width="10%">&nbsp;</th>
 <?
   if( count( $data ) > 0 ) { 
    foreach( $data as $item) {
  ?> 
  </tr>
   <tr bgcolor="#efefef">
   <td><?= $item["id"] ?></td>
   <td><?= empty( $item["title"] ) ? "нет титла" :  $item["title"] ?></td>
   <td><?= $item["node_id"] ?></td>
   <td><?= $item["project_title"] ?></td>
   <td><?= $item["save"] == 0 ? "Не сохранять" : "Сохранять" ?></td>
   <td><a href="index.php?menu=field&item_id=<?= $item["id"]  ?>">Поля</a></td>
   <td><a href="index.php?menu=form&action=edit&id=<?= $item["id"] ?>&item_id=<?= $param["item_id"] ?>" class="menu">редактировать</a></td>
   <td><a href="index.php?menu=form&action=list&cmd=del&id=<?= $item["id"] ?>&item_id=<?= $param["item_id"] ?>" class="menu" onclick="return ConfirmDelete()">удалить</a></td>
   <tr>
  <? 
     }  
   } ?> 
 </table>
 <?= !empty($param["item_id"]) ? '<p align="left"><a href="?menu=node">Узлы</a></p>' : ''?>
<p>&nbsp;</p>