<title>Администрирование</title>
<meta http-equiv="Content-Type" content="text/html; charset=windows-1251">
</head>
<body topmargin="0" leftmargin="0" rightmargin="0">
<script type="text/javascript">

function emptyField(textObj)
{
 if(textObj.value.length==0) return true;
 for(var i=0;i<textObj.value.length;++i)
 {
  var ch=textObj.value.charAt(i);
  if(ch!=' ' && ch!='\t') return false;
 }
 return true;
}


function ConfirmDelete()
{
  if (confirm("Удалить текущую запись?")) return true;
  return false;
}


function IsInt(textObj)
{
 for(var i=0;i<textObj.value.length;++i)
 {
  var ch=textObj.value.charAt(i);
  if(ch<"0" || ch>"9") return false;
 }
 return true;
}
</script>

<style type="text/css">
body {
	margin-left: 0px;
	margin-top: 0px;
	margin-right: 0px;
	margin-bottom: 0px;
	font-family:Arial, Helvetica, sans-serif; 
	background-image: url(/images/bg.jpg);
	
	}

a,a.link,a.visited, a.active {
   font-family:Arial, Helvetica, sans-serif;
   font-size:12px;
   text-decoration:none;
   font-weight:bold;
   color:blue;
  }
  
h1 {
  font-size: 14px;
  font-family:Arial, Helvetica, sans-serif;
  color: maroon;
  }
  
.content_tbl {
   border: 1px Solid gray; 
  
 }
 
 table.menu td {
  font-family:Arial, Helvetica, sans-serif;
  font-size: 13px;
  padding-top: 10px;
 }
 
 table.menu td a{
  font-family:Arial, Helvetica, sans-serif;
  font-size: 13px;
  color: maroon;
  
 }
 
 table.menu td a:hover{
  font-family:Arial, Helvetica, sans-serif;
  font-size: 13px;
  color: maroon;
  text-decoration: underline;
 }
 
 .caption{
 color:black;
 font-size:14px;
 font-weight:bold;
}

.content{
 color:black;
 font-size:12px;
 background-color:white;

}
input{
border: 1px solid black;
}

textarea{
border: 1px solid black;
}


 td{
 padding-left:10px;
 padding-right:10px;
 font-size:12px;

 }

th{
 padding-left:10px;
 padding-right:10px;
 font-size:12px;

 }
</style>

<table cellspacing="0" cellpadding="0" border="0" width="100%" height="100%">
<tr valign="top">
 <td align="left" height="108" width="260" >&nbsp;</td>
 <td align="center" valign="middle" height="108"><h1>Админка</h1></td>
</tr>
<tr valign="top" >
 <td align="left" colspan="2" height="100%">
 
 <table cellpadding="0" cellspacing="0" width="100%"  height="100%" style=" border-collapse: collapse; ">
 <tr valign="top">
  <td align="center" width="15%" class="content_tbl">
  
  <table cellpadding="0" cellspacing="0" width="100%" class="menu">
   
  <tr>
    <td align="left"><a href="?menu=projects"  class="menu">Проекты</a><td>
  </tr>
 <tr>
    <td align="left"><a href="index.php?menu=typefields"  class="menu">Типы полей</a><td>
 </tr>   
  <tr>
   <td align="left"><hr style="border: 1px Solid maroon; border-collapse: collapse;"></td>
  </tr>
  
  <tr>
    <td align="left"><a href="index.php?menu=node"  class="menu">Узлы</a><td>
  </tr>
  
  <tr>
    <td align="left"><a href="index.php?menu=form"  class="menu">Формы</a><td>
  </tr>
  
  <tr>
   <td align="left"><hr style="border: 1px Solid maroon; border-collapse: collapse;"></td>
  </tr>
 <!--  
  <tr>
    <td align="left"><a href="index.php?menu=field"  class="menu">Поля</a><td>
  </tr>  -->
  
  <tr>
    <td align="left"><a href="index.php?menu=references"  class="menu">References</a><td>
  </tr>
  
  <tr>
   <td align="left"><hr style="border: 1px Solid maroon; border-collapse: collapse;"></td>
  </tr>
  
  <tr>
    <td align="left"><a href="index.php?menu=condition"  class="menu">Условия</a><td>
  </tr>
  
  <tr>
   <td align="left"><hr style="border: 1px Solid maroon; border-collapse: collapse;"></td>
  </tr>
  
  <tr>
   <td align="left"><a href="?menu=exit" class="menu">Выход</a></td>
  </tr> 
  </table>
   
  </td>
  <td align="center" width="85%" class="content_tbl" style="padding-top: 10px;">
  <? 
      $this  -> show_inc( "admin" ); 
  ?>
  </td>
 </tr>
 </table>

 </td>
</tr> 
</table>