<?
$param = $this -> get_data( "param" );
$select = $param["country"];

?>
<ul id="left_menu">   
<li><a href="?menu=user"  class="menu">Администраторы</a></li>
<li><a href="?menu=nav"  class="menu">Разделы сайта</a></li>
<li><a href="index.php?menu=articles"  class="menu">Все страницы</a></li>
<li>&nbsp;</li>
<li><a href="?menu=country"  class="menu">Страны</a></li>
<li><a href="?menu=region"  class="menu">Регионы</a></li>
<li><a href="?menu=city"  class="menu">Города</a></li>
<li><a href="?menu=distrib"  class="menu">Дистрибуторы</a></li>
<li><a href="?menu=net"  class="menu">Сети</a></li>
<li>&nbsp;</li>
<li><a href="?menu=torgpred"  class="menu">Торговые представители</a></li>
<li>&nbsp;</li>
<li><a href="?menu=exit" style="color: black;">Выход</a></li>
</ul>
