-- MySQL Script generated by MySQL Workbench
-- 11/29/19 13:56:27
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema komus_new
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema komus_new
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `komus_new` DEFAULT CHARACTER SET utf8 ;
USE `komus_new` ;

-- -----------------------------------------------------
-- Table `komus_new`.`timezones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `komus_new`.`timezones` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `zone` TINYINT(2) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `komus_new`.`regions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `komus_new`.`regions` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `code` VARCHAR(10) CHARACTER SET 'latin1' NULL DEFAULT NULL,
  `subcode` TINYINT(2) UNSIGNED NULL DEFAULT NULL,
  `timezones_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_regions_timezones1_idx` (`timezones_id` ASC),
  CONSTRAINT `fk_regions_timezones1`
    FOREIGN KEY (`timezones_id`)
    REFERENCES `komus_new`.`timezones` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 105
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `komus_new`.`groups_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `komus_new`.`groups_users` (
  `id` INT(11) NOT NULL,
  `groups` VARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `gru_groupid` (`id` ASC),
  INDEX `gru_userid` (`id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `komus_new`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `komus_new`.`users` (
  `user_id` INT(10) NOT NULL AUTO_INCREMENT,
  `user_login` VARCHAR(100) CHARACTER SET 'utf8' NOT NULL,
  `user_password` VARCHAR(32) CHARACTER SET 'utf8' NOT NULL,
  `user_email` VARCHAR(64) CHARACTER SET 'utf8' NOT NULL,
  `user_firstname` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `user_lastname` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `user_gender` CHAR(1) CHARACTER SET 'utf8' NOT NULL,
  `user_birthdate` DATE NOT NULL,
  `user_lastvisit` DATETIME NOT NULL,
  `user_ban` TINYINT(1) NULL DEFAULT NULL,
  `timezones_id` INT(11) NOT NULL,
  `groups_users_id` INT(11) NOT NULL,
  PRIMARY KEY (`user_id`),
  INDEX `user_password` (`user_password` ASC),
  INDEX `fk_users_timezones_idx` (`timezones_id` ASC),
  INDEX `fk_users_groups_users1_idx` (`groups_users_id` ASC),
  CONSTRAINT `fk_users_timezones`
    FOREIGN KEY (`timezones_id`)
    REFERENCES `komus_new`.`timezones` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_groups_users1`
    FOREIGN KEY (`groups_users_id`)
    REFERENCES `komus_new`.`groups_users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1147
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `komus_new`.`contacts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `komus_new`.`contacts` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `creation_time` DATETIME NULL DEFAULT NULL,
  `city` VARCHAR(255) NULL DEFAULT NULL,
  `organization` VARCHAR(100) NULL DEFAULT NULL,
  `address` VARCHAR(255) NULL DEFAULT NULL,
  `fio` VARCHAR(255) NULL DEFAULT NULL,
  `phone` VARCHAR(255) NULL DEFAULT NULL,
  `email` VARCHAR(100) NULL DEFAULT NULL,
  `category` VARCHAR(255) NULL DEFAULT NULL,
  `subcategory` VARCHAR(255) NULL DEFAULT NULL,
  `question` TEXT NULL DEFAULT NULL,
  `allow_call` TINYINT(1) UNSIGNED NOT NULL DEFAULT '1',
  `comment` TEXT CHARACTER SET 'cp1251' NULL DEFAULT NULL,
  `regions_id` INT(11) NOT NULL,
  `users_user_id` INT(10) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_contacts_regions1_idx` (`regions_id` ASC),
  INDEX `fk_contacts_users1_idx` (`users_user_id` ASC),
  CONSTRAINT `fk_contacts_regions1`
    FOREIGN KEY (`regions_id`)
    REFERENCES `komus_new`.`regions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contacts_users1`
    FOREIGN KEY (`users_user_id`)
    REFERENCES `komus_new`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 607
DEFAULT CHARACTER SET = utf8
PACK_KEYS = 0
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `komus_new`.`calls`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `komus_new`.`calls` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `contact_id` INT(11) UNSIGNED NULL DEFAULT NULL,
  `begin_time` DATETIME NULL DEFAULT NULL,
  `end_time` DATETIME NULL DEFAULT NULL,
  `recall_time` DATETIME NULL DEFAULT NULL,
  `status` VARCHAR(50) NULL DEFAULT NULL,
  `contacts_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_calls_contacts1_idx` (`contacts_id` ASC),
  CONSTRAINT `fk_calls_contacts1`
    FOREIGN KEY (`contacts_id`)
    REFERENCES `komus_new`.`contacts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 612
DEFAULT CHARACTER SET = utf8
PACK_KEYS = 0
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `komus_new`.`maillog`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `komus_new`.`maillog` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `DATETIME_` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `log` TEXT NOT NULL,
  `contacts_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_maillog_contacts1_idx` (`contacts_id` ASC),
  CONSTRAINT `fk_maillog_contacts1`
    FOREIGN KEY (`contacts_id`)
    REFERENCES `komus_new`.`contacts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 459
DEFAULT CHARACTER SET = utf8
PACK_KEYS = 0
ROW_FORMAT = DYNAMIC;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
